# Generated by Django 5.2.11 on 2026-05-24 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frame_rate', models.IntegerField(default=30)),
                ('interpolation_factor', models.IntegerField(default=2, help_text='Multiplier factor e.g., 2x, 4x, 8x')),
                ('selected_model', models.CharField(choices=[('RIFE', 'RIFE (Real-Time Intermediate Flow Estimation)'), ('DAIN', 'DAIN (Depth-Aware Video Frame Interpolation)'), ('FILM', 'FILM (Frame Interpolation for Large Motion)'), ('SUPER_SLOMO', 'Super SloMo (Super Slow Motion)')], default='RIFE', max_length=30)),
                ('original_video', models.FileField(blank=True, null=True, upload_to='original_videos/')),
                ('interpolated_video', models.FileField(blank=True, null=True, upload_to='interpolated_videos/')),
                ('progress', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_sequence_frame', models.BooleanField(default=False)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='projects.project')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['frame_number', 'uploaded_at'],
            },
        ),
    ]
